config/routes.rb
Rails.application.routes.draw do
  resources :counters do
    collection do
      post 'serach'
    end
  end
  
end

app/models/counter.rb
class Counter < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/counters_controller.rb
# -*- coding: utf-8 -*-
class CountersController < ApplicationController
  before_action :set_counter, only: [:show, :edit, :update, :destroy]

  # GET /counters
  # GET /counters.json
  def index
    @counters = Counter.all


    score = []
    category = []
    
    @counters.each do |chart|
      if chart.twitime.hour.to_i == params[:id].to_i
        score << chart.sleepcount
        category << chart.twitime.min
      end
    end
    
    p params[:period_to]
    
    @graph = LazyHighCharts::HighChart.new('graph') do |f|
      f.title(text: '眠いカウンター')
      f.xAxis(name:'分',categories: category)
      f.series(name:'ツイート数',data:score)
    end
  end

  # GET /counters/1
  # GET /counters/1.json
  def show
  end

  # GET /counters/new
  def new
    @counter = Counter.new
  end

  # GET /counters/1/edit
  def edit
  end

  # POST /counters
  # POST /counters.json
  def create
    @counter = Counter.new(counter_params)

    respond_to do |format|
      if @counter.save
        format.html { redirect_to @counter, notice: 'Counter was successfully created.' }
        format.json { render :show, status: :created, location: @counter }
      else
        format.html { render :new }
        format.json { render json: @counter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /counters/1
  # PATCH/PUT /counters/1.json
  def update
    respond_to do |format|
      if @counter.update(counter_params)
        format.html { redirect_to @counter, notice: 'Counter was successfully updated.' }
        format.json { render :show, status: :ok, location: @counter }
      else
        format.html { render :edit }
        format.json { render json: @counter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /counters/1
  # DELETE /counters/1.json
  def destroy
    @counter.destroy
    respond_to do |format|
      format.html { redirect_to counters_url, notice: 'Counter was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_counter
      @counter = Counter.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def counter_params
      params.require(:counter).permit(:sleepcount, :twitime)
    end
    

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/counters_helper.rb
module CountersHelper
end

app/views/counters/_form.html.erb
<%= form_for(@counter) do |f| %>
  <% if @counter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@counter.errors.count, "error") %> prohibited this counter from being saved:</h2>

      <ul>
      <% @counter.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :sleepcount %><br>
    <%= f.text_field :sleepcount %>
  </div>
  <div class="field">
    <%= f.label :twitime %><br>
    <%= f.datetime_select :twitime %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
  <div class="field">
    <%= f.text_field :created_at, :size => 15, 
 :class => 'datetimepicker',
 :value => f.object.created_at ? f.object.created_at.strftime('%Y/%m/%d %H:%M') : '' %>
  </div>
<% end %>

app/views/counters/edit.html.erb
<h1>Editing counter</h1>

<%= render 'form' %>

<%= link_to 'Show', @counter %> |
<%= link_to 'Back', counters_path %>

app/views/counters/index.html.erb
<h1>Listing counters</h1>
<p> Date:<input type="text" class="datepicker" /></p>
<p> Date:<input type="text" class="datetimepicker" /></p>


<table>
  <thead>
    <tr>
      <th>Sleepcount</th>
      <th>Twitime</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>

    <% @counters.each do |counter| %>
      <tr>
        <td><%= counter.sleepcount %></td>
        <td><%= counter.twitime %></td>
        <td><%= link_to 'Show', counter %></td>
        <td><%= link_to 'Edit', edit_counter_path(counter) %></td>
        <td><%= link_to 'Destroy', counter, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Counter', new_counter_path %>

app/views/counters/new.html.erb
<h1>New counter</h1>

<%= render 'form' %>

<%= link_to 'Back', counters_path %>

app/views/counters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Sleepcount:</strong>
  <%= @counter.sleepcount %>
</p>

<p>
  <strong>Twitime:</strong>
  <%= @counter.twitime %>
</p>

<%= link_to 'Edit', edit_counter_path(@counter) %> |
<%= link_to 'Back', counters_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sleep</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<!-- Themaは自分の好きなものをDLしてください -->
<link type="text/css" href="/stylesheets/jquery-ui-1.8.9.custom.css" rel="stylesheet" />  

<!-- jqueryui -->                                                                                 
<script type="text/javascript" src="http://www.google.com/jsapi"></script>
<script type="text/javascript">
google.load('jqueryui', '1.8.9');
</script>

<!-- datetimepicker -->
<script type="text/javascript" src="http://trentrichardson.com/examples/timepicker/js/jquery-ui-timepicker-addon.js"></script>
<script type="text/javascript">
$(function(){
  $('.datetimepicker').datetimepicker({
    inline: true,
    dateFormat: 'yy/mm/dd'
  });
});
</script>

<%= yield %>

</body>
</html>